### ISSUE TITLE
Can Gingko be used to determine CNVs from single cell RNA seq data?

### ISSUE THREAD

**Issue by kragrawa** [robertaboukhalil/ginkgo#10]
Hi I wanted to know if Gingko could be used to determine CNVs from single cell RNA seq data, or does the data have to be DOP-PCR and MALBAC data? Thank you!

**Comment by mschatz** [comment]
Ginkgo is only designed for DNA analysis. There have been a few approaches to predict CNVs from RNAseq, but requires a totally different framework to account for the variable expression of genes across different cell types. Good luck! Mike
