### ISSUE TITLE
Genomes data url cannot be accessed.

### ISSUE THREAD

**Issue by zh542370159** [robertaboukhalil/ginkgo#11]
I don't know whether it is my network problem. However, the URL for downloading genomes data cannot be accessed.  
http://labshare.cshl.edu/shares/schatzlab/www-data/ginkgo/genomes/
gives me an error 
**504 Gateway Time-out
The server didn't respond in time.**

**Comment by robertaboukhalil** [comment]
It seems it was down for a bit, but should be back up now!
