### ISSUE TITLE
Uploading issue

### ISSUE THREAD

**Issue by rujinwang** [robertaboukhalil/ginkgo#16]
Hi, 
Ginkgo works well in my previous analyses. But I always fail to upload the .bed inputs now. It seems that files are uploaded successfully. But if I click "next step", there are empty in the "select cells" box. Do you have any idea on this issue?

Thanks, 
RW

**Comment by rujinwang** [comment]
I used [http://qb.cshl.edu/ginkgo/?q=/7IdYTzYQH7NDSFcXtmpW] to upload.

**Comment by mschatz** [comment]
Could you please try again? The server was full that hosts the application,
but I was able to open up a few hundred GB to use

Good luck

Mike

**Comment by robertaboukhalil** [comment]
Closing this, let us know if you still have an issue

**Comment by rujinwang** [comment]
Thanks for all your kind help!

Best,
Rujin
