### ISSUE TITLE
server down?

### ISSUE THREAD

**Issue by proukakis** [robertaboukhalil/ginkgo#18]
hi, we haven't been able to upload anything since yesterday (either adding to existing, or new instances). It seems to work and then when the upload reaches 100% says Error Failed to write file to disk. thanks

**Comment by mschatz** [comment]
Can you please try again? The server that hosts the application ran out of
space, but I just cleared a few hundred GB

Good luck

Mike

**Comment by proukakis** [comment]
many thanks, works, really useful

**Comment by wmyuan37** [comment]
Hi, thanks for developing this amazing tool! I would like to see the result of a new dataset, when I did that, it seems that the same issue happen again, could you please clear out some space? Thank you!
