### ISSUE TITLE
Lorenz-based cutoff metric?

### ISSUE THREAD

**Issue by kunalkathuria** [robertaboukhalil/ginkgo#23]
Hello,

I was wondering if there is a built-in metric (or e.g. a way to use the normalized bin counts post-analysis) to identify "bad cells" (similar to having a BIC score for each cell) ?

Thanks,

Kunal

**Comment by robertaboukhalil** [comment]
A good starting point would be the `SegStats` file, e.g. [here](http://qb.cshl.edu/ginkgo/uploads/_t10breast_navin/SegStats?uniq=1211447). I don't think we currently output GC stats + MAD values in the GUI, but if you run it through the CLI, you could probably infer those values and use them for quality check. Hope this helps!

**Comment by kunalkathuria** [comment]
Thank you! I may also be looking at Lorenz curve deviations for each cell.
