### ISSUE TITLE
Bad Bin -> coordinate map?

### ISSUE THREAD

**Issue by kunalkathuria** [robertaboukhalil/ginkgo#24]
I was wondering if there is a file somewhere that would map bin numbers to genomic hg 19 coordinates (e.g. for 500 kb variable bins) so that I can know which regions are masked by the bad-bin analysis? Thank you,

Kunal

**Comment by robertaboukhalil** [comment]
Hi Kunal, yes, in the files you downloaded that contain the genome coordinates, there should be a file that looks something like e.g. `variable_500000_101_bowtie`, where the line number (excluding the header) should be the bin ID

**Comment by kunalkathuria** [comment]
Thank you!
