### ISSUE TITLE
Running cells with second-best SoS solution?

### ISSUE THREAD

**Issue by laurenhummel** [robertaboukhalil/ginkgo#25]
Hi there,

I am using Gingko (CLI mostly) and am wondering if there is a way to re-run a small subset of cells to provide data from the second-best SoS solution? I have some cases where the least error and second least error are extremely close and I wish to look at certain cells/the output data under another copy number solution.

If not, could you point me to the appropriate place in the code to try making my own alterations? (Sorry, I am new to bioinformatics!!)

Thanks so much!

Lauren

**Comment by robertaboukhalil** [comment]
Hi Lauren,

Unfortunately Ginkgo doesn't currently support that, but if you'd like to modify the code, you would need to update [this section of `process.R`](https://github.com/robertaboukhalil/ginkgo/blob/master/scripts/process.R#L211).

Specifically, [line 223](https://github.com/robertaboukhalil/ginkgo/blob/master/scripts/process.R#L223) defines the value of `CN`. Currently, it says `CN = CNmult[1,k]`, where the `1` in `[1,k]` means it uses the 1st least error for cell with ID `k`. I would start by stepping through that code to see if using `[2,k]` for example would help for a given cell `k` of interest.

Hope this helps!

Robert
