### ISSUE TITLE
bounds_variable files

### ISSUE THREAD

**Issue by kunalkathuria** [robertaboukhalil/ginkgo#26]
Hi Robert,

I am trying to run Ginkgo with a list of bad bins generated outside of Ginkgo. I was trying to understand the nature of the chromosome bounds listed in the two different bounds_variable_{binSize}etc. files. Could you help? Thank you!

--Kunal

**Comment by robertaboukhalil** [comment]
The files `bounds_variable_<binsize>_<readlength>_<aligner>` contain 2 columns: the chromosome number, and the global bin number corresponding to the last bin for that chromosome.

e.g. `bounds_variable_1000000_150_bwa`: `chr3	650` means the last bin of chromosome 3 is the 650th line in the `variable_1000000_150_bwa` file.

**Comment by kunalkathuria** [comment]
Thank you!
