### ISSUE TITLE
Something about reference

### ISSUE THREAD

**Issue by jasminexiao** [robertaboukhalil/ginkgo#27]
Hi , Robert ! I used gingko to call CNV pattern nowadays， using different references. The results were the same whether I used normal or CNV samples as controls. And I was sure  my parameter settings were correct, can you provide me with some suggestions ?

**Comment by robertaboukhalil** [comment]
Hey, a few questions:

1. Do you have a link to the two Ginkgo analyses that show you the same result?
2. Which kinds of samples are you using as "normal" and "CNV samples"? 
3. For the CNV sample, are there specific/known CNVs you're expecting to see?
4. What do you mean by "using different references", do you mean difference reference genomes?

Thanks,

**Comment by jasminexiao** [comment]
Dear Sir,
Thank you for your reply.
Q1, the attachments are the three files I used and the detail is in the README.md file.
Q2, "normal samples" are 46,XX/XY samples, "CNV samples" are aneuploid samples.
Q3, CNV patterns of these samples are called by HMMcopy, so I know the CNV patterns  accurately.
Q4, different references refer to uploading different files as controls, not to the genome of the species. (segMeth=2 in config files)


Best wishes.











--

陈依东
Chen Yidong



At 2019-12-05 13:11:26, "Robert Aboukhalil" <notifications@github.com> wrote:


Hey, a few questions:

Do you have a link to the two Ginkgo analyses that show you the same result?
Which kinds of samples are you using as "normal" and "CNV samples"?
For the CNV sample, are there specific/known CNVs you're expecting to see?
What do you mean by "using different references", do you mean difference reference genomes?

Thanks,

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

从网易163邮箱发来的云附件
Icm01-W-s12.bed.gz (166.84M, 2019年12月20日 15:37 到期)
下载
Icm03-W-s58.bed.gz (273.57M, 2019年12月20日 15:38 到期)
下载
Icm10-Q-s246.bed.gz (228.99M, 2019年12月20日 15:39 到期)
下载
README.md (700B, 2019年12月20日 15:40 到期)
下载

**Comment by robertaboukhalil** [comment]
Do you have Ginkgo URLs where you ran these analyses? I can't see the file attachments here.
