### ISSUE TITLE
Web-platform: Error Gateway Time-out

### ISSUE THREAD

**Issue by silvainp** [robertaboukhalil/ginkgo#28]
Hello all,
I try to upload some bed.gz files (25-150Mb) to use the web-platform of Ginkgo but I still have this Error Gateway Time-out. Could you please let me know how to fix it?
Many thanks for your help.

**Comment by robertaboukhalil** [comment]
Yes, we sometimes see intermittent problems with our current hosting. Could you give it another try?

**Comment by silvainp** [comment]
Thanks it is working now. many thanks for the tool! I would like to download a better version of the GC bias plot. Is there a way to download the data for this plot?

**Comment by robertaboukhalil** [comment]
We don't have a way to download that data from the GUI directly, but here is the code you can run for generating GC plots: https://github.com/robertaboukhalil/ginkgo/blob/master/scripts/analyze-subset.R#L127
