### ISSUE TITLE
Analysis time

### ISSUE THREAD

**Issue by yifnzhao** [robertaboukhalil/ginkgo#32]
Hi,

I am wondering what would be the approximate time for the analysis. I uploaded 3 .beg.gz files (~90 MB each) and it says 80% complete after 6h. Is this normal? I also got the Gateway Time Out error several times when uploading the files. [Here](http://qb.cshl.edu/ginkgo?q=results/yP5ogFEHm98nFgNugQm8) is the link to my analysis. Thanks!

**Comment by yifnzhao** [comment]
Analysis time problem resolved - it was because one of my files was corrupted. The gateway time out error seems to be quite persistent.

**Comment by robertaboukhalil** [comment]
Closing issue since it sounds like the problem was resolved
