### ISSUE TITLE
CNV1 vs CNV2?

### ISSUE THREAD

**Issue by kunalkathuria** [robertaboukhalil/ginkgo#33]
I was wondering what the difference is between these 2 CNV outputs? Thanks!

**Comment by kunalkathuria** [comment]
CNV1 seems to have more calls than CNV2 for some samples I ran.

**Comment by robertaboukhalil** [comment]
The [CNV1 file](http://qb.cshl.edu/ginkgo/uploads/_t10breast_navin/CNV1) lists copy-number events where the last column = copy number, whereas the [CNV2](http://qb.cshl.edu/ginkgo/uploads/_t10breast_navin/CNV2) file lists regions with amplifications (+1) and deletions (-1)--see the last values of the last column of these files
