### ISSUE TITLE
duplicates/secondaries

### ISSUE THREAD

**Issue by kunalkathuria** [robertaboukhalil/ginkgo#34]
Hi Robert,

Does Ginkgo remove duplicate and/or secondary alignments before processing reads?

Thanks!

**Comment by jherrero** [comment]
No, the input to Ginkgo are BED files. Yo need to remove those mappings (duplicate, secondary and poor alignment probably as well) before generating the BED files.

**Comment by kunalkathuria** [comment]
True, I realized that afterward sorry. Thank you for the reply.
