### ISSUE TITLE
Stalling during copy number calling (initializing variables)

### ISSUE THREAD

**Issue by andrewrlynch** [robertaboukhalil/ginkgo#35]
Hi there. 

I am running into an issue with web-based Ginkgo where the process is stalling at Step 2: Calling copy number events (initializing variables). 

I am hoping someone can look into this. The URL for the run is http://qb.cshl.edu/ginkgo?q=results/h5rA5DuQbAlom56RDZLj

Be well,

Andrew

**Comment by robertaboukhalil** [comment]
Hi Andrew, looking at the "Analysis Options", I noticed your files have the `#` character in them. I'm not 100% sure that's the issue, but could you try renaming them to remove that character? It's possible Ginkgo doesn't know how to handle those properly.

**Comment by andrewrlynch** [comment]
That was absolutely the issue. I found this to be the case in stand in standalone Ginkgo first and, although it wasn't abundantly obvious, seemed to be the case in web-based Ginkgo. 

Thanks!
