### ISSUE TITLE
Bad bin is not provided in pre-calculated hg19 genome

### ISSUE THREAD

**Issue by liuzhenyu-yyy** [robertaboukhalil/ginkgo#36]
Hi. I'm trying to run ginkgo on my own server. It seems that the bad bin files for hg19 genome "ginkgo/genomes/hg19/original/badbins_*" was not included in the genome data downloaded from http://labshare.cshl.edu/shares/schatzlab/www-data/ginkgo/genomes/. And the link http://qb.cshl.edu/ginkgo/uploads/hg19.original.tar.gz is dead. Is there any advice on how may I download the bad bin files? Thanks a lot.

**Comment by robertaboukhalil** [comment]
That's odd, they should have been in the tar.gz files. You can get the badbins from http://qb.cshl.edu/ginkgo/genomes/hg19/original/badbins_variable_100000_101_bowtie. You can change the file name with different bin size options

**Comment by liuzhenyu-yyy** [comment]
Thanks for the immediate reply. That's really helpful.
