### ISSUE TITLE
Web-platform: doesn't work

### ISSUE THREAD

**Issue by dulunar** [robertaboukhalil/ginkgo#37]
I want to upload some bed files (small size) to the web-platform for calling CNV, but I found it did not work. When I finished the upload and continue the newt step, it returned back to the upload step.

Another, the Sample analyses are also broken, it can be clicked to select the previous datasets for testing.

**Comment by mschatz** [comment]
Thanks for your interest. Can you please try again? The backend server
recently filled up, but was able to free up some space now.

I also dont follow your problem with the sample analyses - this seems to be
working just fine, for example:
http://qb.cshl.edu/ginkgo/?q=results/_t10breast_navin

Thanks!

Mike
