### ISSUE TITLE
Analysis stuck at 66%

### ISSUE THREAD

**Issue by RudolfWach** [robertaboukhalil/ginkgo#38]
I have started various analyses since last week and none of them get past 66% completion. Also, the file uploading was a challenge with many unsuccessful uploads (error: true / error: bad gateway). Smaller gzip compressed files seem to upload a little more easily. Sometimes files that first didn`t upload, suddenly get displayed in the "STEP 1" overview.

Is it the server, or could my files be the issue? (although, files that I analyzed successfully in the past show the same behavior)

Thanks!

**Comment by WeichenZhou** [comment]
@RudolfWach did you solve the problem here? I can see my jobs stuck at 67% for a night as well....
