### ISSUE TITLE
The input file format

### ISSUE THREAD

**Issue by biowumin** [robertaboukhalil/ginkgo#39]
Hi, thank you for providing this tool for CNV analysis. I want to use ginkgo to infer CNV of single cells, and I wonder  the input files format, that is, the bed file and the FACS file. One bed file contains one cell? Can you provide an example? Thank you so much!

**Comment by robertaboukhalil** [comment]
That's right, 1 bed file = 1 cell. You'll find instructions on what those bed files should look like/how to generate them on the sidebar at http://qb.cshl.edu/ginkgo, under "Help". As for the FACS file, the format is a tab-separated file with 2 columns: the cell name, and the estimated ploidy.
