### ISSUE TITLE
standalone ginkgo: SegCopy not found?

### ISSUE THREAD

**Issue by biocyberman** [robertaboukhalil/ginkgo#4]
I am running a test run via web interface after setting up ginkgo. 

The analysis is stuck at `step 2: 0% Calling copy number events... ( Initializing variables)`

Cheking ginkgo.out under the analysis folder, I can see several trials to read the `SegCopy` file. 
`

```
awk: fatal: cannot open file '/mnt/data/ginkgo/uploads/80OSyT7WskAjdEZslogZ/SegCopy' for reading (No such file or directory)
```

**Comment by biocyberman** [comment]
Some progress:

I tracked down to the problem when rerunning the failed analysis. First I configured the `genome` directory incorrectly so the analysis failed. I then restarted the analysis, but it does not really restart. This is because variable `init` in `config` file is still set to `0`. Changed it to 1 and made some progress now.

**Comment by robertaboukhalil** [comment]
Are you still getting an error message after you made that change?

**Comment by biocyberman** [comment]
I works now. Sorry for the delayed response. It's a question of understand how the program work and configure correctly.

**Comment by robertaboukhalil** [comment]
Glad to hear that, thank you!

**Comment by robertaboukhalil** [comment]
`SegCopy` should be in the output of each analysis, and not in the genome tar
