### ISSUE TITLE
Failed to upload the .bed or .bed.gz

### ISSUE THREAD

**Issue by wmyuan37** [robertaboukhalil/ginkgo#44]
Hello,

I am currently experiencing an issue while attempting to upload multiple .bed or .bed.gz files to the website. Even though the website indicates that the files have been uploaded successfully, they do not appear in the selection panel post-clicking the 'Analyze' button. I have observed this issue on multiple PCs, suggesting that it may not be a local issue.

Given the consistent occurrence of this problem, it would be greatly appreciated if you could investigate the potential root causes behind this situation.

Thank you for your time and assistance with this matter.

**Comment by mschatz** [comment]
Please try again - the backend server filled up but I cleaned out some space

Good luck!

Mike

**Comment by wmyuan37** [comment]
Solved!
Thank you!
