### ISSUE TITLE
Phylogenetic Tree output?

### ISSUE THREAD

**Issue by jmfa** [robertaboukhalil/ginkgo#5]
Dear Robert,

I'm currently using the standalone version of ginkgo and am wondering how can I build a phylogenetic tree from the data?
In the web-based platform, there's a tree in the results (which according to the paper is estimated by "first computing the Pearson correlation between all samples and using these dissimilarity values to cluster the samples").  However, in the standalone version, I don't get such tree. Instead, I just get the different dendrograms derived from the heatmaps.

**Comment by jherrero** [comment]
The dendrograms are the different trees that Ginkgo pre-computes. You get all the trees in JPEG, in PDF, in XML (phyloXML) and in Newick format. If you want to read the tree in R, have a look at the ape package. If you are after the interactive tree, I am afraid the standalone version does not offer that functionality.

I hope this helps

**Comment by jmfa** [comment]
Right, yes. I was looking for the interactive tree.
Thanks for the quick and helpful reply, @jherrero.

**Comment by robertaboukhalil** [comment]
Thanks @jherrero!
