### ISSUE TITLE
BWA bin boundaries disagree with bowtie bin boundaries

### ISSUE THREAD

**Issue by mschatz** [robertaboukhalil/ginkgo#6]
The BWA bins are determined by finding perfect matches (using a grep for NM:i:0) but doesnt confirm that the alignment is unique. Should check H0 and/or MQ to confirm uniqueness.

**Comment by robertaboukhalil** [comment]
Is mapping quality >= 30 a good threshold? See pull request #7

**Comment by mschatz** [comment]
Yes, looks good!

**Comment by robertaboukhalil** [comment]
Merged!
