### ISSUE TITLE
How to define the reference sample?

### ISSUE THREAD

**Issue by anyone1985** [robertaboukhalil/ginkgo#8]
I have some MALBAC single cell data. I'd like to analyze the CNV with ginkgo. I do not know how to define the normal sample in the config file. Please give me some example to follow.

**Comment by tgarvin** [comment]
Hi. You need to also provide Malbac single cell read data in bed format for a cell that you know is from normal diploid tissue (I.e. from a tissue that has no major copy number variations).

If you didn't sequence any cells from a known normal diploid cell line you can download sequencing data from any previously generated dataset in the same organism/cell line. However, it's always better to have data from the same sequencing runs to control for any other errors introduced in the process.

Sent from my iPhone

On Aug 1, 2017, at 11:25 PM, anyone1985 <notifications@github.com<mailto:notifications@github.com>> wrote:


I have some MALBAC single cell data. I'd like to analyze the CNV with ginkgo. I do not know how to define the normal sample in the config file. Please give me some example to follow.

**Comment by anyone1985** [comment]
Yeah. I have malbac single cell data from blood and adjacent. How do I define this data in the config file? Another question is if ginkgo could output the range of LOH. Because I need this data for SciClone analysis ? Thank you for your quick reply.

**Comment by robertaboukhalil** [comment]
In the GUI, under _Segmentation_, select _Custom_ and upload the reference `.bed` file.

If you're using the CLI, you can define `segMeth=2` and `ref=yourRefFile.bed` in the config.

Let us know if that fixes your issue.

**Comment by anyone1985** [comment]
Thank you for your answer.
