### ISSUE TITLE
problem in the R code

### ISSUE THREAD

**Issue by RichardCorbett** [robertaboukhalil/ginkgo#9]
Hi there,

I'm setting up a local install of ginko and running a set of just over 900 single cell libraries.   After installing all the required libraries I had to make a small change to the code:

 line 25 of analyze.sh is looking for a folder called "genomes" this isn't in my install so I took it out and got much farther.

Now I get to the part when lots of .jpegs are being created and I get an error that I have narrowed down to this location:
```
/opt/ginkgo/scripts/process.R /opt/ginkgo/genomes/hg19 /opt/ginkgo/uploads/CIC1 status.xml data 0 variable_100000_150_bwa ward.D2 euclidean 1 refDummy.bed_mapped 0 ploidyDummy.txt 1 0
Loading required package: amap
Loading required package: methods

Attaching package: ‘gplots’

The following object is masked from ‘package:stats’:

    lowess

Error in clip(tu[1], mean(temp) - (diff(reads$mids)/2), tu[3], tu[4]) : 
  invalid 'x2' argument
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted

```
I get this error after getting though 102 libraries for which I get lots of pretty .jpeg images.

Looking in the status.xml file I am able to narrow this down to happening on just one of my libraries. That particular library doesn't looking very different from the others.    

Do you have any suggestions I could try ?

**Comment by tgarvin** [comment]
Does that library have a very low number of mapped reads compared to the others?

Sent from my iPhone

On Aug 2, 2017, at 11:51 AM, Richard Corbett <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,

I'm setting up a local install of ginko and running a set of just over 900 single cell libraries. After installing all the required libraries I had to make a small change to the code:

line 25 of analyze.sh is looking for a folder called "genomes" this isn't in my install so I took it out and got much farther.

Now I get to the part when lots of .jpegs are being created and I get an error that I have narrowed down to this location:

/opt/ginkgo/scripts/process.R /opt/ginkgo/genomes/hg19 /opt/ginkgo/uploads/CIC1 status.xml data 0 variable_100000_150_bwa ward.D2 euclidean 1 refDummy.bed_mapped 0 ploidyDummy.txt 1 0
Loading required package: amap
Loading required package: methods

Attaching package: ‘gplots’

The following object is masked from ‘package:stats’:

    lowess

Error in clip(tu[1], mean(temp) - (diff(reads$mids)/2), tu[3], tu[4]) :
  invalid 'x2' argument
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted



I get this error after getting though 102 libraries for which I get lots of pretty .jpeg images.

Looking in the status.xml file I am able to narrow this down to happening on just one of my libraries. That particular library doesn't looking very different from the others.

Do you have any suggestions I could try ?

**Comment by RichardCorbett** [comment]
The BAM has roughly the same amount of reads as the others, but I just realized that the .bed.gz for that one is empty.  I'm starting from scratch to see if this happens again.

**Comment by tgarvin** [comment]
Great let me know if you have any other questions.

Sent from my iPhone

On Aug 2, 2017, at 1:04 PM, Richard Corbett <notifications@github.com<mailto:notifications@github.com>> wrote:


The BAM has roughly the same amount of reads as the others, but I just realized that the .bed.gz for that one is empty. I'm starting from scratch to see if this happens again.

**Comment by RichardCorbett** [comment]
Restarting from scratch solved the problem. Thanks for the help.
